/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./buttons/UiButton.vue')['default']
    UiRadioGroup: typeof import('./buttons/radio/UiRadioGroup.vue')['default']
    UiRadioItem: typeof import('./buttons/radio/UiRadioItem.vue')['default']
    UiTextField: typeof import('./fields/UiTextField.vue')['default']
    UiThinButton: typeof import('./buttons/UiThinButton.vue')['default']
  }
}
